/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/BillScanning`; params?: Router.UnknownInputParams; } | { pathname: `/CreateProfilePage`; params?: Router.UnknownInputParams; } | { pathname: `/HealthyShopperSummary`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/LoginPage`; params?: Router.UnknownInputParams; } | { pathname: `/MoneySaverPage`; params?: Router.UnknownInputParams; } | { pathname: `/MoneySaverProgress`; params?: Router.UnknownInputParams; } | { pathname: `/MoneySaverSummary`; params?: Router.UnknownInputParams; } | { pathname: `/RegistrationPage`; params?: Router.UnknownInputParams; } | { pathname: `/ScanBillScreen`; params?: Router.UnknownInputParams; } | { pathname: `/ScanHealthy`; params?: Router.UnknownInputParams; } | { pathname: `/SelectStylePage`; params?: Router.UnknownInputParams; } | { pathname: `/TimeSaverPage`; params?: Router.UnknownInputParams; } | { pathname: `/TimeSaverSummary`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/styles/CreateProfilePage`; params?: Router.UnknownInputParams; } | { pathname: `/styles/LoginPage`; params?: Router.UnknownInputParams; } | { pathname: `/styles/RegistrationPage`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/BillScanning`; params?: Router.UnknownOutputParams; } | { pathname: `/CreateProfilePage`; params?: Router.UnknownOutputParams; } | { pathname: `/HealthyShopperSummary`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/LoginPage`; params?: Router.UnknownOutputParams; } | { pathname: `/MoneySaverPage`; params?: Router.UnknownOutputParams; } | { pathname: `/MoneySaverProgress`; params?: Router.UnknownOutputParams; } | { pathname: `/MoneySaverSummary`; params?: Router.UnknownOutputParams; } | { pathname: `/RegistrationPage`; params?: Router.UnknownOutputParams; } | { pathname: `/ScanBillScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/ScanHealthy`; params?: Router.UnknownOutputParams; } | { pathname: `/SelectStylePage`; params?: Router.UnknownOutputParams; } | { pathname: `/TimeSaverPage`; params?: Router.UnknownOutputParams; } | { pathname: `/TimeSaverSummary`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/CreateProfilePage`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/LoginPage`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/RegistrationPage`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/BillScanning${`?${string}` | `#${string}` | ''}` | `/CreateProfilePage${`?${string}` | `#${string}` | ''}` | `/HealthyShopperSummary${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/LoginPage${`?${string}` | `#${string}` | ''}` | `/MoneySaverPage${`?${string}` | `#${string}` | ''}` | `/MoneySaverProgress${`?${string}` | `#${string}` | ''}` | `/MoneySaverSummary${`?${string}` | `#${string}` | ''}` | `/RegistrationPage${`?${string}` | `#${string}` | ''}` | `/ScanBillScreen${`?${string}` | `#${string}` | ''}` | `/ScanHealthy${`?${string}` | `#${string}` | ''}` | `/SelectStylePage${`?${string}` | `#${string}` | ''}` | `/TimeSaverPage${`?${string}` | `#${string}` | ''}` | `/TimeSaverSummary${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/styles/CreateProfilePage${`?${string}` | `#${string}` | ''}` | `/styles/LoginPage${`?${string}` | `#${string}` | ''}` | `/styles/RegistrationPage${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/BillScanning`; params?: Router.UnknownInputParams; } | { pathname: `/CreateProfilePage`; params?: Router.UnknownInputParams; } | { pathname: `/HealthyShopperSummary`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/LoginPage`; params?: Router.UnknownInputParams; } | { pathname: `/MoneySaverPage`; params?: Router.UnknownInputParams; } | { pathname: `/MoneySaverProgress`; params?: Router.UnknownInputParams; } | { pathname: `/MoneySaverSummary`; params?: Router.UnknownInputParams; } | { pathname: `/RegistrationPage`; params?: Router.UnknownInputParams; } | { pathname: `/ScanBillScreen`; params?: Router.UnknownInputParams; } | { pathname: `/ScanHealthy`; params?: Router.UnknownInputParams; } | { pathname: `/SelectStylePage`; params?: Router.UnknownInputParams; } | { pathname: `/TimeSaverPage`; params?: Router.UnknownInputParams; } | { pathname: `/TimeSaverSummary`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/styles/CreateProfilePage`; params?: Router.UnknownInputParams; } | { pathname: `/styles/LoginPage`; params?: Router.UnknownInputParams; } | { pathname: `/styles/RegistrationPage`; params?: Router.UnknownInputParams; };
    }
  }
}
